// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20220704175353_AddSeedDataForCountriesAndHotels")]
    partial class AddSeedDataForCountriesAndHotels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alpha3Code = "CAN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 2,
                            Alpha3Code = "DNK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 3,
                            Alpha3Code = "SWE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 4,
                            Alpha3Code = "NOR",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 5,
                            Alpha3Code = "CHE",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 6,
                            Alpha3Code = "AUS",
                            Name = "Australia"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "108 Chestnut St, Toronto, ON, M5G1R3",
                            CountryId = 1,
                            Name = "Relax Moose Resort",
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 2,
                            Address = "6546 Fallsview Blvd, Niagara Falls, ON, L2G2W2",
                            CountryId = 1,
                            Name = "Beaver Spa",
                            Rating = 3.9m
                        },
                        new
                        {
                            Id = 3,
                            Address = "143 York St, Sydney NSW 2000, Australia",
                            CountryId = 6,
                            Name = "Yes Hotel",
                            Rating = 4.8m
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
